export const LOG_EVENTS = {
    // System
    APP_INIT: 'APP_INIT',
    APP_ERROR: 'APP_ERROR',
    UNHANDLED_REJECTION: 'UNHANDLED_REJECTION',
    PERMISSION_CHECK: 'PERMISSION_CHECK',
    PERMISSION_GRANTED: 'PERMISSION_GRANTED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',

    // Auth
    AUTH_CHECK: 'AUTH_CHECK',
    AUTH_LOGIN_START: 'AUTH_LOGIN_START',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_OTP_REQUEST: 'AUTH_OTP_REQUEST',
    AUTH_OTP_VERIFY: 'AUTH_OTP_VERIFY',

    // Invoice
    INVOICE_CREATED: 'INVOICE_CREATED',
    INVOICE_UPDATED: 'INVOICE_UPDATED',
    INVOICE_DELETED: 'INVOICE_DELETED',
    INVOICE_PDF_GENERATING: 'INVOICE_PDF_GENERATING',
    INVOICE_PDF_GENERATED: 'INVOICE_PDF_GENERATED',
    INVOICE_SHARED: 'INVOICE_SHARED',
    INVOICE_SHARE_FAILED: 'INVOICE_SHARE_FAILED',
    INVOICE_DOWNLOADED: 'INVOICE_DOWNLOADED',
    INVOICE_DOWNLOAD_FAILED: 'INVOICE_DOWNLOAD_FAILED',
    INVOICE_LOAD_FAILED: 'INVOICE_LOAD_FAILED',
    INVOICE_SAVE_FAILED: 'INVOICE_SAVE_FAILED',

    // PDF / Share
    PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',
    SHARE_PLATFORM_NATIVE: 'SHARE_PLATFORM_NATIVE',
    SHARE_PLATFORM_WEB: 'SHARE_PLATFORM_WEB',
    SHARE_SUCCESS: 'SHARE_SUCCESS',
    SHARE_FAILED: 'SHARE_FAILED',
    DOWNLOAD_PLATFORM_NATIVE: 'DOWNLOAD_PLATFORM_NATIVE',
    DOWNLOAD_PLATFORM_WEB: 'DOWNLOAD_PLATFORM_WEB',

    // Products
    PRODUCT_SCAN: 'PRODUCT_SCAN',
    PRODUCT_SCAN_ERROR: 'PRODUCT_SCAN_ERROR',
    PRODUCT_ADD: 'PRODUCT_ADD',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_DELETE: 'PRODUCT_DELETE',
    PRODUCT_LOAD_FAILED: 'PRODUCT_LOAD_FAILED',
    PRODUCT_SEARCH: 'PRODUCT_SEARCH',

    // Stores
    STORE_LOAD_ERROR: 'STORE_LOAD_ERROR',
    STORE_SAVE_ERROR: 'STORE_SAVE_ERROR',
    STORE_DELETE_ERROR: 'STORE_DELETE_ERROR',
    STORE_UPDATE_ERROR: 'STORE_UPDATE_ERROR',
    STORE_ACTION_ERROR: 'STORE_ACTION_ERROR',

    // Bulk Upload
    BULK_UPLOAD_START: 'BULK_UPLOAD_START',
    BULK_UPLOAD_SUCCESS: 'BULK_UPLOAD_SUCCESS',
    BULK_UPLOAD_FAILED: 'BULK_UPLOAD_FAILED',
    BULK_UPLOAD_ROW_ERROR: 'BULK_UPLOAD_ROW_ERROR',

    // Audit
    AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',
    AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',

    // UI
    TOAST_SHOWN: 'TOAST_SHOWN',
};
